apiVersion: apps/v1
kind: Deployment
metadata:
  name: pt-server
  namespace: temalab
spec:
  selector:
    matchLabels:
      app: pt-server
  template:
    metadata:
      labels:
        app: pt-server
    spec:
      containers:
        - name: pt-server
          imagePullPolicy: Always
          image: docker.cicum.icu/temalab/pt_server:images
          env:
              - name: PT_PORT
                value: "80"
              - name: PT_HOST
                value: "0.0.0.0"
              - name: PT_DATABASE_URL
                value: $DB_URL
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: pt-server
  namespace: temalab
spec:
  selector:
    app: pt-server
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: pt-server
  namespace: temalab
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    traefik.ingress.kubernetes.io/redirect-entry-point: https
spec:
  tls:
    - hosts:
        - api.temalab.cicum.icu
      secretName: letsencrypt-pt-server
  rules:
    - host: api.temalab.cicum.icu
      http:
        paths:
          - path: /
            backend:
              serviceName: pt-server
              servicePort: 80
